[general]
shuffle_caption = true
caption_extension = ".txt"
keep_tokens = 0
flip_aug = false

[[datasets]]
resolution = 512
batch_size = 1
enable_bucket = true
min_bucket_reso = 512
max_bucket_reso = 1024
bucket_reso_steps = 64

[[datasets.subsets]]
image_dir = "/path/to/train_images"
num_repeats = 1
